name: PrisonCore
author: Trig
version: 1
main: com.trig.vn.prison.Prison
depend: [VNDB]
commands:
  rankup:
    description: Rankup command
  achievement:
    description: Main achievement command
  backpack:
    description: View what is in your backpack