name: PrisonCore
author: Trig
version: 1
main: com.trig.vn.prison.Prison
depend: [VNDB, NPCHandler, Essentials, WorldEdit, VNEssentials, VNCrates]
commands:
  rankup:
    description: Rankup command
  achievement:
    description: Main achievement command
  backpack:
    description: View what is in your backpack
  prison:
    description: VN Prison admin commands
  bloat:
    description: Bloat your chat
  sell:
    description: Automatically sell your inventory